### ISSUE TITLE
Cursive joining has gaps

### ISSUE THREAD

**Issue by dscorbett** [notofonts/chorasmian#3]
### Font 
NotoSansChorasmian-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/chorasmian/releases/tag/NotoSansChorasmian-v1.003
Date: 2023-09-25

### Font version
Version 1.003

### Issue
The medial aleph that is supposed to join above the baseline has a gap after it.

The initial and medial forms of gimel do not always join the following glyph.

After taw, a medial aleph does not join the following glyph.

There is a gap between taw and many other letters, like pe.

### Character data
<span dir="ltr">𐾲𐾰𐾸</span>
U+10FB2 CHORASMIAN LETTER BETH
U+10FB0 CHORASMIAN LETTER ALEPH
U+10FB8 CHORASMIAN LETTER ZAYIN

<span dir="ltr">𐾳𐾴</span>
U+10FB3 CHORASMIAN LETTER GIMEL
U+10FB4 CHORASMIAN LETTER DALETH

<span dir="ltr">𐿄𐾰𐾾</span>
U+10FC4 CHORASMIAN LETTER TAW
U+10FB0 CHORASMIAN LETTER ALEPH
U+10FBE CHORASMIAN LETTER NUN

<span dir="ltr">𐿄𐿁</span>
U+10FC4 CHORASMIAN LETTER TAW
U+10FC1 CHORASMIAN LETTER PE

### Screenshot
![𐾲𐾰𐾸](https://github.com/notofonts/chorasmian/assets/1124347/3d975aea-ebee-458a-89ea-321a5c42522a)
![𐾳𐾴](https://github.com/notofonts/chorasmian/assets/1124347/33a51ab1-0bf6-4055-97a1-cd314d909dad)
![𐿄𐾰𐾾](https://github.com/notofonts/chorasmian/assets/1124347/7d58b76e-847f-46a2-b453-00dadc0ebb06)
![𐿄𐿁](https://github.com/notofonts/chorasmian/assets/1124347/a6890889-3473-49b3-b4c3-e702cfdc112d)

**Comment by simoncozens** [comment]
I've done what I can with this, but there are probably still some gaps remaining. A long text sample we have looks reasonable, do let me know if you notice anything else.
